### PR TITLE
add enum to primitiveFields

### LINKED ISSUE #42: support returning enums in queries
I'm trying to get the value of an enum in for a given type. given the following schema:

```
enum ItemType {
  EVENT
  NOTE
  TASK
}

type Item {
  id: ID!
  title: String!
  type: ItemType!
}

type Query {
  item(id: ID!): Item!
  items: [Item!]!
}
```

I'm trying to do:

```
  const { error, loading, data: items } = useQuery((store) =>
    store.queryItems({}, (item) => item.type.title),
  )
```

however it seems that `type` isn't available in this case. Sorry if this is a known issue with enums!

### PR DESCRIPTION
**Pull request by chrisdrackett**
closes #42

### CODE REVIEW

**Comment by chrisdrackett** [comment]
@elie222 @mweststrate I'm using this and the other PR's I've authored in our project without issue, but I didn't want to just merge without a review. Let me know if there is a process around this and if I need to do anything else like update or add to the examples related to these changes!

**Comment by elie222** [comment]
We just need to bump the version and do a new publish to npm

**Comment by mweststrate** [comment]
@elie222 @chrisdrackett I think you both have publish permissions to npm? Otherwise let me know your username, and I'll add you, so you aren't blocked by somebody else releasing. (I typically use `yarn publish` as that prompts for the version as well)

**Comment by elie222** [comment]
I have permission. Will update soon. Fixing failing tests now.

**Comment by chrisdrackett** [comment]
@mweststrate looks like I don't have permission on npm (just tried to do a release): https://www.npmjs.com/~chrisdrackett

**Comment by mweststrate** [comment]
Should have permission now!

**Pull request merged**
