### PR TITLE
Use `relative-deps` to keep library in sync with examples

### LINKED ISSUE #32: `realpath` missing when running examples
When running the examples I ran into this issue when running `yarn install`:

```sh
../../scripts/install-mst-gql.sh: line 6: realpath: command not found
```

Doing this fixed it for me:

```sh
npm install --global realpath
```

`realpath-native` does get installed in the root `node_modules` folder. Should the example bash script be updated to rely on the copy of `realpath` in `node_modules`?

### PR DESCRIPTION
**Pull request by mweststrate**
I've generalized the installation script that keeps the lib build in sync with the examples, into a separate tool [relative-deps](https://github.com/mweststrate/relative-deps), to make this process simpler and faster. 

Also fixes #32

### CODE REVIEW

**Comment by dpnolte** [comment]
Just for your reference, there is a 5th example added with the merge of #22 . That example probably needs to be updated as well.

**Comment by mweststrate** [comment]
@dpnolte the migration is straight-forward enough, so shouldn't cause much trouble: https://github.com/mobxjs/mst-gql/pull/40/commits/4d2c0858f8c44a562c0244466b56f79b0ed7591b

Any idea why the build is failing? Master build seems to be failing as well

**Comment by dpnolte** [comment]
You mean 'build and test' job on circle-ci?

One of the tests is failing for generating interfaces types. This should be fixed by #39.
The issue was that interfaces type were filtered out by filtering on `type.kind !== "INTERFACE"`. Somehow this got creeped in. In the test, it was checked whether the ModelSelector was generated for the interface, but it wasn't due to this issue.

Can I merge #39?

**Comment by mweststrate** [comment]
LGTM :)

**Comment by elie222** [comment]
I see CI is working now. When does it decide to run on a PR and does it skip it? Or was this setting updated today?

**Comment by mweststrate** [comment]
I rebased on master and pushed again 😊

Op zo 23 jun. 2019 20:10 schreef Elie <notifications@github.com>:

**Pull request merged**
