### PR TITLE
Prettier Baseline

### PR DESCRIPTION
**Pull request by chrisdrackett**
- upgrade prettier
- update prettierignore
- run prettier on entire project to get a baseline
- setup pretty-quick for pre-commit prettier formatting

### CODE REVIEW

**Comment by elie222** [comment]
Need to fix merge conflicts :(

**Comment by chrisdrackett** [comment]
I think merging #57 might help avoid some conflicts as right not editing a file can result in a lot of unrelated prettier changes

**Comment by elie222** [comment]
Yes. That one also has merge conflicts now. But have approved for merge.

**Comment by chrisdrackett** [comment]
I think getting this one in ASAP will help avoid future conflicts. I'll update it now

**Comment by elie222** [comment]
Still got a conflict. May be due to another pr I accepted just now

**Pull request merged**
