### PR TITLE
WIP: Semantic release

### PR DESCRIPTION
**Pull request by elie222**
@mweststrate still need to set up the auth stuff with npm, but I think you have to do that as project owner

### CODE REVIEW

**Comment by elie222** [comment]
Will test this under my own npm account first.

See these for enforcing commit messages. Hope this isn't annoying for contributors:
https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6
https://github.com/kreuzerk/node-command-line-starter/blob/master/package.json
https://github.com/commitizen/cz-cli/issues/161#issuecomment-485207911

If we don't enforce certain commit messages, then we can write a note about it in the README or in the PR template similar to:
https://github.com/mobxjs/mobx/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by dpnolte** [comment]
Awesome stuff! Maybe it is an idea to also run CI on open pull requests to prevent - for example - test snapshot failures? This would probably involve changing CircleCI settings (see sections 'Configuring CircleCI' and 'Opening a pull request' @ https://circleci.com/blog/automatically-deploy-a-gatsby-site-to-firebase-hosting/ )

**Comment by elie222** [comment]
Yup. I think that makes sense.

I’ve accidentally merged 2 prs with failing tests already. Only seeing the
circle ci email after the merge was complete.

**Comment by mweststrate** [comment]
Just to be sure, this PR is not blocking on me currently, or is it?

**Comment by elie222** [comment]
No, it's not. It's a very simple PR, but I got sidetracked and want to test
it out a bit better before merging.

**Pull request closed without merging**
