### PR TITLE
add correct query hook type

### PR DESCRIPTION
**Pull request by mattiasewers**
fixes the ci build

### CODE REVIEW

**Comment by veeral-patel** [comment]
@mweststrate Hey -- had the same question. How should we iterate over our data with this new query type?

Thanks for the project btw!

**Comment by beepsoft** [comment]
@veeral-patel Well, I just reverted back to `data: DATA | undefined` and it works fine from there on.

**Comment by mattiasewers** [comment]
I cannot replicate this, try upgrading typescript

**Comment by beepsoft** [comment]
@mattiasewers I just checked out the project and built it using the TS version provided by the project (3.5.3) and I get this error:
```
..../examples/1-getting-started/src/app/Home.tsx
Error:(14, 23) TS2339: Property 'map' does not exist on type '{ todos: TodoModelType[]; }'.
Error:(14, 27) TS7006: Parameter 'todo' implicitly has an 'any' type.
```

**Comment by beepsoft** [comment]
Could it be related to this?

https://github.com/microsoft/TypeScript/issues/6041

**Comment by mattiasewers** [comment]
@beepsoft nope, you were right this is a bug. I have rewritten the type implementation again and it should be correct now, I'll have a pr shortly

**Comment by beepsoft** [comment]
@mattiasewers Great, thank you for your effort!

**Comment by veeral-patel** [comment]
@beepsoft Hey -- thanks for your reply! What did you mean by this? Did you change your mst-gql version?

> @veeral-patel Well, I just reverted back to data: DATA | undefined and it works fine from there on.

**Comment by beepsoft** [comment]
@veeral-patel I replaced every occurence of `{[key: string]: DATA}` or` {[key: string]: T}` to `DATA` and `T` respectively in the code (in react.tsx and Query.ts). (In earlier versions of mst-gql that's how these were defined).

But let's wait for @mattiasewers coming up with a better solution!

**Pull request merged**
