### PR TITLE
Allow LIST to be optional in TS

### LINKED ISSUE #165: LIST always interpreted as required
These two definitions will both result in required values for `ids`, in other words, I cannot omit the value from my query. One of them has "ids" as required and other does not. However, even if I do not make `ids` required, the typescript definition will not have a "?" on it, making it optional ie `variables: { ids: string[] }`. It should be `variables: { ids?: string[] }` when it is not required. This will work correctly when it is not a LIST, and just a normal scalar. I now have to add `{ids: undefined}` so that my TS compiler does not complain.

```
    {
                  "name": "ids",
                  "description": null,
                  "type": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                      "kind": "NON_NULL",
                      "name": null,
                      "ofType": {
                        "kind": "SCALAR",
                        "name": "ID",
                        "ofType": null
                      }
                    }
                  },
                  "defaultValue": null
                }
```

AND

```
 {
                  "name": "ids",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "LIST",
                      "name": null,
                      "ofType": {
                        "kind": "NON_NULL",
                        "name": null,
                        "ofType": {
                          "kind": "SCALAR",
                          "name": "ID",
                          "ofType": null
                        }
                      }
                    }
                  },
                  "defaultValue": null
                }
```

### PR DESCRIPTION
**Pull request by Aryk**
Closes #165

### CODE REVIEW

**Comment by Aryk** [comment]
Hey @zenflow - I saw you were active on some recent code reviews. Can you take a look at this when you get a chance? This is a pretty fundamental bug I feel since an optional list is a pretty common use-case. 

Thanks in advance

**Comment by zenflow** [comment]
@Aryk Sure, I'd be happy to! But I won't be really able to for about a week. Feel free to ping me then, if I don't get around to it beforehand.

**Comment by mattiasewers** [comment]
@zenflow can this be merged?

**Comment by Aryk** [comment]
Hey @zenflow any updates on this one?

**Comment by chrisdrackett** [comment]
@Aryk sorry for the delay on this, I saw that it looked like @zenflow was going to get to it so I didn't look back.

**Comment by Aryk** [comment]
No problem, thanks for merging. Excited to use the new release.

Just curious, when will there be a new version on npm?

**Comment by chrisdrackett** [comment]
`0.10.0` is up now, let me know if you run into issues!

**Pull request merged**
