### PR TITLE
Add optional filter option to localStorageMixin

### PR DESCRIPTION
**Pull request by reekris**
Allows the user to filter which data to store in local storage

- Uses `lodash/pick` since it allows to use dot notation for filtering nested data which is nice. But maybe there's a better alternative?

### CODE REVIEW

**Comment by zenflow** [comment]
@reekris What is the use case for this? Would it be more generally useful to accept a function, which can filter or transform the data in any way, rather than accepting an array of object paths?

**Comment by reekris** [comment]
In my case I only want to store a users logged in token and some user settings and not the entire store. A problem can arise if the entire store is persisted and a key changes, then the entire cache is discarded when loaded. I my case that would mean that the users logged in state is lost.  

When looking at this I found a TODO comment about adding a key filter in the localStorageMixin file, so thats the way I implemented it. But I like your idea of supplying a function instead for more flexibility, maybe at the cost of ease of use. Do you want me to adjust the Pull request with this change?

**Comment by zenflow** [comment]
> Do you want me to adjust the Pull request with this change?
@reekris I'm not actually using this package or looking after it anymore, so that's not really for me to say. I just thought I would contribute my two cents :)

I'm still not sure if anyone would ever need to filter or transform the data in any *different* way than this (`pick`ing only certain key paths), so maybe this way is better since it's easier to use 🤷

**Comment by reekris** [comment]
@chrisdrackett May I ask why this issue was closed? This functionality is mentioned as a TODO in the source code: https://github.com/mobxjs/mst-gql/blob/104d0a9c237fbb6b34287442936c69928b1d6760/src/localStorageMixin.ts#L11

**Comment by chrisdrackett** [comment]
I don’t remember closing this so it must have been a mistake

**Comment by chrisdrackett** [comment]
I’m really confused how this happened. I wasn’t even awake when in theory I closed this :/

**Comment by chrisdrackett** [comment]
oh, I see what happened. We renamed the `master` branch `main` and when the old master branch got deleted all the PR's got closed. Please re-open this, and sorry, that's my bad!

**Pull request closed without merging**
