### PR TITLE
Feat - support interface and union field types

### PR DESCRIPTION
**Pull request by dpnolte**
Hi,

I also needed support for interface and union fields types. I received the error mesage: "PRs are welcome" :) So with this PR, i'd like to submit my proposal for supporting them.

In parsing the GraphQL types, the Interfaces are mapped to the implementing objects, and unions are mapped to its member types. With this mapping, it is possible to resolve the abstract interface/field types to a union of all the concrete objects. That is, each interface/union will be defined as `types.union(...)` in the mst model, and the union constitutes out of the concrete objects implementing the interface or are the members of the union. I thought this solution was more concise and simpler than creating new models for interfaces/unions.

Secondly, interfaces and unions require inline fragments to select object-specific data. With this PR, the QueryBuilder will be able to produce something like:
```graphql
query {
  getAllRepos {
   name
   ... on User {
     avatar
   }
   ... on Organization {
     logo
   }
 }
}
```

Looking at the files, there are many changes (Sorry!). But most of it is the result from scaffolding output. The key changes can be found in:
* generate.js
* queryBuilder.ts
and tests in:
* generate.test.js
* /tests/lib/abstractTypes/abstractTypes.test.js

Below is a walkthrough of the main changes:
**Generate.js**
- `resolveInterfaceAndUnionTypes`: Besides inlining interfaces, this method resolves union and interfaces to its member types and the implementing objects and returns this mapping.
- `handleInterfaceOrUnionFieldType`: generates mst union from the graphql interfaces/unions
- Splitted `handleObjectType`
  - Created `resolveFieldsAndImports` that resolve (non-)primitive field types and imports. This can now be used by handleObjectType and handleInterfaceOrUnionType
  -  Moved out `generateFragments`. This method now generates model selectors for objects, interfaces, and unions. The interfaces and unions field types will be resolved as `this.__inlineFragment` a new method of the QueryBuilder. For interfaces, the interface fields are used to determine the PrimitivesModel. For unions, the PrimitiveModel constitutes out of all the primitive fields of the union's member types.
- `handleInterfaceOrUnionType` is added to generate the ModelSelectors for abstract types (i.e, interfaces and unions). These model selectors can be used to select data from unions and interfaces. The generated files are named `${name}ModelSelector` to make it distinctive from model files (TBC). 
  
**QueryBuilder.js**
- `__inlineFragment` generates inline fragments like `... on User`
- `__buildChild` was previously part of __child to defined child properties. This is now also used by __inlineFragment. Also, this method also now accepts already instantiated QueryBuilders (aka childBuilder) to populate child attributes. This enables to use primitive models as model selector for the children (see below).

**Primitive Models**
Another change is that the primitive models are no longer strings. That is, `toString()` is no longer called. Instead, primitive models are being kept as QueryBuilder instances. This allowed me to use primitive models and add more variables to select, e.g.:
```typescript
repoModelPrimitives.owner(ownerModelPrimitives)
```
Albeit that the library has a young age, I guess this can be considered a breaking change.

In `generate.test.js`,I have  added tests for generating with union and interface field types. Additionally, I have added tests in /tests/lib/abstractTypes for testing generating valid graphQL queries and loading the store and models.

I hope it is clear. Please consider every point as proposal. I just wanted something that was already working and start from there :) I also think that it would be great if generate.js could be refactored into multiple files (happy to help). Maybe also add a linter and transpile it with typescript/babel as well?

### CODE REVIEW

**Comment by mweststrate** [comment]
Looking great!

@elie222 would you be interested in creating a release for this? I can walk you trough it.

**Comment by elie222** [comment]
Yes. Happy to. Let me know the steps

**Comment by dpnolte** [comment]
I've added some further changes:
- **Imports** - tweaked importing
  - simplified it by combining model imports and direct imports, and prevent errors when importing enums model selectors as they don't exist
  - fixed a newline issue
- **printTsTypes** - At the moment, enums are incorrectly typed in typescript. Enums don't have the same type name as objects. Instead, I have typed enums and input objects as any for the time being.  A warning is printed to the user when this happens. If an unknown type is encountered, an error is still being thrown.

**Comment by elie222** [comment]
@mweststrate What needs doing here?
Bump version, Merge PR, tag release, and publish to npm?

**Comment by mweststrate** [comment]
@elie222 sorry for the late response! Was abroad last week. 

Yes, it isn't automated yet, but the steps are

1. Fill out `changelog.md` and commit (I don't think I created one yet, alternatively, it could be interesting to setup up semantic-release tool)
2. Run `yarn build && yarn publish && git push && git push --tag`. Yarn publish will ask for a new version number, and IIRC it will tag automatically as well.

**Comment by elie222** [comment]
So I just made a PR to add semantic release:
https://github.com/mobxjs/mst-gql/pull/38

It would do a new publish every time there's a change to master, handle changelog, tagging, etc. Is this the sort of setup we want or you'd prefer to manually publish which seems to be the case for Mobx?

**Comment by mweststrate** [comment]
I think automated is great! Just make sure it is documented how people
should commit in the README :)

**Comment by elie222** [comment]
@mweststrate i bumped the version and updated changelog on master, but only you have permission to run `yarn publish` since you're the one behind the `mst-gql` on npm.

**Comment by elie222** [comment]
@dpnolte I already merged this to master, but I see we have a failing test for interfaces:

https://circleci.com/gh/mobxjs/mst-gql/42

**Comment by mweststrate** [comment]
Sorry, thought I did so already! Too many projects 😅. What is your npm
user name?

Op vr 21 jun. 2019 09:36 schreef Elie <notifications@github.com>:

**Comment by elie222** [comment]
No worries. I realise you're very busy. NPM username is: elie222

**Comment by mweststrate** [comment]
Done!

**Pull request merged**
