### PR TITLE
Fix handling of union of root types

### LINKED ISSUE #304: GraphQL union type fields aren't created as references
If a model contains a Union type object, we end up with
`types.union(types.late(() => AreaModel), types.late(() => ScheduleModel))`

when it should actually be
`MSTGQLRef(types.union(types.late(() => AreaModel), types.late(() => ScheduleModel)))`

Because it's not creating it as a reference, it will fail to load the snapshot, as it will try to create a duplicate object of the Union'd type instead of referencing the existing object in the RootStore map.

I'm guessing this is may be because only roots are turned into MSTGQLRef's elsewhere, and union types of course not being turned into roots

### PR DESCRIPTION
**Pull request by smokku**
Properly generate `MSTGQLRef()`s for union type fields.

Fixes #304

### CODE REVIEW

**Comment by jesse-savary** [comment]
Hey @smokku, thank you for this. I had to pass `null` for `fieldArgs` when calling `handleObjectFieldType` as I merged another of your PRs. I'm planning on doing a bunch of testing this week with mst-gql before cutting a new release but I was wondering if you could help out specifically with this fix so I can verify I didn't break it :)

**Comment by smokku** [comment]
Just checked my local `generate.js` and this is the proper change, with both PR merged, with one difference:
```js
return handleObjectFieldType(t.name, t, fieldArgs, false, true)
```
but `null` works too. ;-)

**Comment by smokku** [comment]
For completeness, here is the full diff og `generate.js` I use on production: https://gist.github.com/smokku/5df4400e898d9805f45ddbb3af1180c5

**Comment by jesse-savary** [comment]
Great -- I'll get this patched up before release, thank you!

**Comment by adumat** [comment]
@smokku thanks a lot!

**Pull request merged**
