### PR TITLE
feat: added option to not generate react scaffold

### LINKED ISSUE #15: React should be opt-in or opt-out
I think the generation of the code related to React should be an opt-in feature. Store management should be agnostic. 

Or at least, it should be possible to give an **option to not output React code**.

### PR DESCRIPTION
**Pull request by ematipico**
Added an option `--noReact` that prevents from generating react files.

Closes #15

### CODE REVIEW

**Comment by dpnolte** [comment]
I was wondering if the peer dependency on mobx-react can then also be removed as part of this PR. At first glance, it seems that this peer dep is not necessary anyways? And perhaps react-dom can also be removed?

**Comment by ematipico** [comment]
Yes you are right. Although if the user decides to scaffold the react snippets, somehow we have to notify the user that they have to add these libraries in their dependencies. How should we tackle this?

**Comment by FredyC** [comment]
That's why I was suggesting a plugin architecture in #15. If the actual React bindings would be a plugin, it can have `mobx-react` as a dependency without the need to be in the core package.

**Comment by ematipico** [comment]
Which will be part of #13 and using a better CLI tool such as Gluegun

**Comment by FredyC** [comment]
Well, I don't really see a point in adding some option now when it will become obsolete once a proper tool is used :) It seems that Gluegun indeed supports plugins, so that would solve it.

**Comment by dpnolte** [comment]
@FredyC How do you think that plugin architecture should look like? 
It seems that the plugin would apply mostly to the scaffolding output and the related required dependencies such as react/mobx-react. Additionally, the usQuery hook (react.tsx) needs to be moved to this plugin. Also perhaps nice to have a mobx-react-light plugin.

I guess it would be easiest to add a plugin section to a config file here (see also #8 ).
Using cosmiconfig, it can parse a plugin array that contains a string array of plugin module names.
I was thinking each plugin can than have a function as default export (similar to babel plugins), but with at least the following arguments:
- module name (e.g, TodoModelBase)
- RootStore import path (e.g., './RootStore')
- toExport array 
- generateFile function to add files as output
This should be sufficient to generate the react utils in the plugin.

The scaffolder (generate.js) could then invoke all configured plugins.
I need to have a solution like the above. So if this makes sense, I can give it a go.

**Comment by FredyC** [comment]
@dpnolte That definitely sounds like a good way to go.

Regarding the mobx-react dependency, why is it actually needed? I don't see it used in any generated code. Sure, you would most likely need it in the app to attach an observer to a component, but that's application concern. That means people can use mobx-react-lite if they want just fine.

One approach that could be interesting is wrapping the `useQuery` body into a `useObserver` and that way it wouldn't be required to use observer for the component. It could be an option of the plugin perhaps because in that case you do you need either `mobx-react-lite` or `mobx-react@6`.

**Comment by mweststrate** [comment]
I think for now the peer deps could be removed and documented. I don't
think plugins solve the problem, as it is related to package published to
npm, not the scaffolded code. (Publishing separate package will be a lot of
work, as one would need to align the release, versioning etc. of the
runtime package with the scaffold package)

Op wo 29 mei 2019 11:53 schreef Daniel K. <notifications@github.com>:

**Comment by dpnolte** [comment]
I see, thanks for explaining. Is there also a way to remove the react peer dependency so that we only have
```json
  "peerDependencies": {
    "graphql": "^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0",
    "graphql-tag": "^2.0.0",
    "mobx": "^4.0.0 || ^5.0.0",
    "mobx-state-tree": "^3.0.0"
  },
```
I guess this means moving createUseQueryHook in react.tsx to a separate package or dynamically require react

**Comment by mweststrate** [comment]
Looking at it, graphql-tag and graphql could actually also removed.
Removing the peer deps doesn't change anything for how the deps are
actually handled, they are just a hint to the package managers that a
warning should be printed if they are absent / incompatible. Requires are
always dynamic, regardless whether you specify dependencies at all or not :)

**Comment by FredyC** [comment]
> Requires are always dynamic, regardless whether you specify dependencies at all or not :)

Sadly it's not true with Webpack which would crash when it sees dependency that's missing. Since everything is bundled into a single dist file, there is no way clear way for optional dependency.

Does that mean we would need runtime plugins as well? It could get messy fairly quickly if we ever decide to support eg. Preact, Vue and whatever.

**Comment by dpnolte** [comment]
Yes, I had made a quick example without add react as dependency: https://codesandbox.io/s/mhf4g
Webpack throws a DependencyNotFoundError.

Although not the cleanest solution, I was thinking of using require.resolve() or System.import and catching it

**Comment by mweststrate** [comment]
I might be missing something, but as host app you still need to install
react and such, it is just that as a package you don't have to specify it.
So afaik webpack should work correctly if `mobx mobx-react react reactdom
mst-gql` are all installed in your project

**Comment by mweststrate** [comment]
Note that with peer deps you also have to do that!

**Comment by FredyC** [comment]
@mweststrate That's not the point :) As long as `react` is referenced in a bundled file, Webpack would fail when you don't have it installed. That's important if you want to only use mobx models, but not the `useQuery`.

**Comment by dpnolte** [comment]
I'm sorry if my comments contributed to the confusion. My use case is to use mst-gql without react. For my use case, it would be great if any react related dependencies would not be mandatory to run mst-gql. That is, I don't have to add react then to my app anymore. That is why in the example I didn't add react etc to the host app. 

If this is out-of-scope, I understand. But if there is something that I can do to make the react dependencies optional in this package, then I'm happy to help :)

**Comment by mweststrate** [comment]
Ah check I get it now. Probably this can be fixed by having react.ts as
separate entry point, or even easier, by passing React as argument to the
hooks factory rather than importing it.

Op wo 29 mei 2019 13:18 schreef dpnolte <notifications@github.com>:

**Comment by dpnolte** [comment]
Cool solution! I'll create a PR for that :)

**Comment by mweststrate** [comment]
Thanks!

**Comment by mweststrate** [comment]
Ok, just merged #16, so it can be added on top of that!

Op wo 29 mei 2019 13:47 schreef dpnolte <notifications@github.com>:

**Comment by mweststrate** [comment]
Released as 0.1.2. Thanks @ematipico & @dpnolte !

**Pull request merged**
