### PR TITLE
MobX 6 Support

### LINKED ISSUE #284: Compatibility with MobX version 6
Can we update to MobX v6 when using mst-gql?
Or should we wait for a compatible release?

### PR DESCRIPTION
**Pull request by BradenM**
Adds support for MobX 6

Upgraded appropriate packages and ran the [mobx-undecorate](https://www.npmjs.com/package/mobx-undecorate) codemod to make the few required changes.

Caused one minor type issue that was easily resolved.

Currently working fine in one of my soon-to-be production react-native applications.

Also :cherries: picked @special-character 's `babelrc` changes from #288 to fix the test suite.

Closes #284

### CODE REVIEW

**Comment by mattiasewers** [comment]
@BradenM Thanks for this, I've tested this and it looks good!

Great if someone else could test this as well @chrisdrackett @special-character

**Comment by beepsoft** [comment]
It works for me as well.

_Note that with the latest mst-state-tree (6.1.4) you get this error https://github.com/mobxjs/mobx-state-tree/issues/1653, which will be hopefully fixed soon. So for now I just use "6.0.4" as you did, and with that it works all right._

**Comment by gorhom** [comment]
@beepsoft this been fixed with [Version 5.0.1](https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.1)

**Comment by weglov** [comment]
Hi, what about the new version of the package? there seems to be a lot of changes since version 0.13.0

**Pull request merged**
